[env]
ADDRESS = "127.0.0.1:7878"
MAX_THREADS = "6"
MAX_BUF_SIZE = "1024"
MAX_POOL_SIZE = "1024"
STREAM_READ_TIMEOUT = "1000"
STREAM_WRITE_TIMEOUT = "1000"
PUBLIC_DIR = "../react-app/build"
ROOT_FILE = "index"
COMPILE_TO = "src"